version: '3.7'
services:
  web:
    build: ./build
    image: odoo_app
    container_name: odoo_app_container
    depends_on:
      - mydb
    ports:
      - "18365:8069"
    environment:
      - HOST=mydb
      - USER=myuser
      - PASSWORD=mypassword
    restart: always
  mydb:
    image: arm32v7/postgres:12
    container_name: odoo_app_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myuser
      - POSTGRES_USER=mypassword
    restart: always
